### PR TITLE
new glTF 2.0 models

### PR DESCRIPTION
**Pull request by sbtron**
New glTF 2.0 models built using PBR workflow - Boombox, Corset and Lantern

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @sbtron!

**Comment by pjcozzi** [comment]
@sbtron could you please add these to the main [README.md](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0#gltf-20-sample-models)?

And also fix the screenshot link in each README?
* https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoomBox
* https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Corset
* https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Lantern

**Comment by emackey** [comment]
@sbtron @pjcozzi Since these are sample models, can we have a better texturemap naming system than what's used here?  For example:

```
BoomBox_image0.png
BoomBox_image1.png
BoomBox_image2.png
BoomBox_image3.png
BoomBox_image4.png
```

Maybe the names could be `BoomBox_ao.png`, `BoomBox_normal.png`, `BoomBox_metallic.png`, `BoomBox_roughness.png`, or something like that?

The models look great BTW!

**Comment by pjcozzi** [comment]
We can't enforce naming conventions for all the contributed sample models, but I agree it would be nice to have these first models named well.

**Comment by bghgary** [comment]
Here you go: https://github.com/KhronosGroup/glTF-Sample-Models/pull/32

**Comment by pjcozzi** [comment]
@bghgary or @sbtron could you also make updates based on these comments: https://github.com/KhronosGroup/glTF-Sample-Models/pull/31#issuecomment-281214041

**Comment by bghgary** [comment]
Done. #33

**Pull request merged**
