### PR TITLE
add Interpolation Test

### PR DESCRIPTION
**Pull request by Reon90**
Spec: [animation sampler.interpolation](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#animation-samplerinterpolation)

### CODE REVIEW

**Comment by lexaknyazev** [comment]
@Reon90 
Please fix the validation error: 
```
/images/0: Recognized image format 'image/jpeg' does not match declared image format 'image/png'.
```
A proper action here is to save that image as an actual PNG file. Also `image.name` and `image.mimeType` could be safely omitted.

**Comment by cx20** [comment]
I have tested this model with [gltf-test](https://github.com/cx20/gltf-test#simple-models-for-testing-individual-features).
The current status is as follows.
image

**Comment by 06wj** [comment]
@cx20 
As discussed in https://github.com/cx20/gltf-test/pull/48#issuecomment-446993361 , the animation of this model is not in the recommended format, so many engines only one box has animation.

**Comment by emackey** [comment]
@06wj In this case I think it's helpful to be able to turn the animations on and off individually.  If they were all a single animation, there would be no way to reduce the amount of noise.

I suggested a new `allAnimations` flag in https://github.com/cx20/gltf-test/pull/57

**Comment by bghgary** [comment]
> If they were all a single animation, there would be no way to reduce the amount of noise.

FWIW, there are asset generator tests that test individual animation types.
https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Animation_Node

**Pull request merged**
