### PR TITLE
Develop/gltf sample viewer enhancements

### PR DESCRIPTION
**Pull request by UX3D-haertl**
This PR adds models which were previously used for the sample viewer

### CODE REVIEW

**Comment by cx20** [comment]
Some models seem to have cases where the file name differs from the folder name. Following convention, it is more consistent to match file and folder names. Since [SheenChair](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SheenChair) already exists, it would be better to place it in a different folder.

Below are the proposed changes.

|before                                                      |after                                |
|:-----------------------------------------------------------|:------------------------------------|
|ClearcoatRing/glTF/**PBR - Metallic Roughness Alpha-blend**.gltf|ClearcoatRing/glTF/**ClearcoatRing**.gltf|
|SheenChair/glTF/**gltf_sheen_damask**.gltf                      |**SheenDamask**/glTF/**SheenDamask**.gltf    |

**Comment by cx20** [comment]
@UX3D-haertl Thank you for the improvement. 
I think the readme and screenshot also need to be added.

|Model Nmae          |README.md         |screenshot        |
|:-------------------|:----------------:|:----------------:|
|ClearcoatRing       |:white_check_mark:|:white_check_mark:|
|ClearcoatSphere     |:x:               |:x:               |
|SheenDamask         |:x:               |:x:               |
|SheenHighHeel       |:x:               |:white_check_mark:|
|TransmissionSuzanne |:x:               |:x:               |

**Comment by cx20** [comment]
I experimentally tried the `ClearcoatRing` model with [gltf-test](https://cx20.github.io/gltf-test/).
However, the display result of each library seems to be different.
I could not determine if the problem with the see-through back was a model problem or a library problem.

|||
|:----------:|:---------------:|
|[image](https://github.khronos.org/glTF-Sample-Viewer-Release/)|[image](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=ClearcoatRing&scale=5&type=glTF)|
|[image](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=ClearcoatRing&scale=5&type=glTF)|[image](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=ClearcoatRing&scale=5&type=glTF)|

**Comment by cx20** [comment]
I also checked `SheenDamask`. This model seems to look quite different from library to library when viewed from an angle.

|||
|:------:|:------:|
|[image](https://github.khronos.org/glTF-Sample-Viewer-Release/)|[image](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=SheenDamask&scale=0.1&type=glTF)|
|[image](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=SheenDamask&scale=0.1&type=glTF)|[image](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=SheenDamask&scale=0.08&type=glTF)|

**Comment by donmccurdy** [comment]
>  However, the display result of each library [for ClearcoatRing] seems to be different.

The ClearcoatRing materials are all using `"alphaMode": "BLEND"` — I think that would be a mistake in this case.

**Comment by cx20** [comment]
@donmccurdy Thank you for your advice.
I tried removing the `alphaMode` property of the material locally to test it out.

https://github.com/KhronosGroup/glTF-Sample-Models/blob/develop/gltf-sample-viewer-enhancements/2.0/ClearcoatRing/glTF/ClearcoatRing.gltf#L244

Results appear to be good.

image

**Comment by DrX3D** [comment]
The automated validation failed. We would like to get this merged in the next week if everything is clean and good to go.

**Comment by DrX3D** [comment]
@echadwick-wayfair , @emackey : Please make a final review of the models

**Comment by UX3D-haertl** [comment]
Yes it is ready from my side

**Pull request merged**
