### PR TITLE
New model testing out vertex colors in COLOR_0

### PR DESCRIPTION
**Pull request by emackey**
This model tests out vertex colors in your rendering engine.  If it works, it looks like this:

screenshot

Really I built this just to review AnalyticalGraphicsInc/cesium#6089.  Vertex colors are being added to Cesium, but not available in master yet as of this writing.  This is the kind of thing you see when vertex colors are not implemented:

sample_fail

There are "X" marks in the "wrong" color channels, and the X's can only be hidden when the vertex colors are correctly applied.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Looks cool, anyone want to review this?

**Comment by donmccurdy** [comment]
Passes validation, works in three.js, and here's the ZIP version:

[Uploading VertexColorTest.zip…]()

Looks good to me.

**Comment by cx20** [comment]
I confirmed that this model can be displayed with 3 libraries.
https://github.com/cx20/gltf-test#agi-sample-models

image
BTW, Hilo3d can display BoxVertexColors.gltf, but it does not pass the test of VertexColorTest.gltf. Is it a problem with the library?

**Comment by emackey** [comment]
> Hilo3d can display BoxVertexColors.gltf, but it does not pass the test of VertexColorTest.gltf. Is it a problem with the library?

The main difference is that VertexColorTest.gltf also uses a mesh and a material *without* vertex colors, in the same model as one that does use vertex colors.  This combination revealed a bug in Cesium's upcoming implementation which has since been fixed (but not yet released, 1.42 should have vertex color support).

I don't know if that's the same problem that Hilo3d has.  The other difference is that this model is testing `VEC3` colors while the other model tests `VEC4` colors, that could be a factor too.

**Comment by cx20** [comment]
I confirmed that it has been fixed by the latest version of Hilo3d.
As for Cesium, I would like to test it again when a new version comes out.

**Comment by pjcozzi** [comment]
@cx20 I believe Cesium will be fixed in Cesium 1.42 on Feb 1.

@lilleyse can you confirm?

**Comment by lilleyse** [comment]
Yes it will be in Cesium 1.42.

**Comment by cx20** [comment]
I confirmed that the test model will be displayed in Cesium 1.42.
https://github.com/cx20/gltf-test#agi-sample-models
image

**Comment by pjcozzi** [comment]
@cx20 cool, thanks for testing so promptly!

**Pull request merged**
