### PR TITLE
Add the Sponza model.

### PR DESCRIPTION
**Pull request by emackey**
This is @Themaister's glTF conversion of the Sponza model, and this pull request is from his repo.

This was originally merged in #175, but there were requests to make this smaller.  Master has been force-pushed to back out the larger version, and this is the new replacement PR for the smaller version.

### CODE REVIEW

**Comment by emackey** [comment]
Thanks @Themaister for bearing with us on this 😄

**Comment by lexaknyazev** [comment]
@emackey Was the model changed to clean validation issues? I don't see them in the report.

**Comment by emackey** [comment]
I believe @Themaister did that.  I don't see any validation issues from VSCode either.

**Comment by cx20** [comment]
@emackey I think that it is no problem to merge PR of this version.

I tried it with @donmccurdy's [gltf-viewer](https://gltf-viewer.donmccurdy.com/) of and I think that Issue of validation is solved.

old version:
image

net version:
image

**Comment by lexaknyazev** [comment]
@cx20 Just in case, could you check it with the latest [online validator](https://github.khronos.org/glTF-Validator)?

**Comment by cx20** [comment]
@lexaknyazev  I tried again with [online validator](http://github.khronos.org/glTF-Validator/). I think there is no problem.

old version:
image

new version:
image

**Comment by Themaister** [comment]
Yes, I fixed those issues. This is expected.

**Pull request merged**
