### PR TITLE
More z forward

### PR DESCRIPTION
**Pull request by emackey**
This updates several models I contributed to use the +Z forward convention.

It also adds `.glb` files for several of them, thanks to najadojo's contributions in AnalyticalGraphicsInc/gltf-vscode#35.

@sbtron @bghgary These models can be tested in Win10's viewer now ("Mixed Reality Viewer", although I'm just using it as a normal desktop previewer).  DamagedHelmet.glb looks amazing.  NormalTangentTest.glb shows errors with the normal vectors, we should investigate.  And somehow TextureSettingsTest.glb is kind of a mess.

### CODE REVIEW

**Comment by emackey** [comment]
Hmm, the validator is spitting out errors on DamagedHelmet:

> #/accessors/3: Accessor element at index `11043` is not of unit length: `0.0`.

This model came from the official Blender exporter.

**Comment by emackey** [comment]
Fixed!  Turns out the previous `DamagedHelmet` was exported without tangent vectors, so that's what I've done for this update as well.  All of these models pass validation now.

This is ready to merge.

**Comment by emackey** [comment]
@bghgary @sbtron I did confirm that Win10 Mixed Reality Viewer is using "DirectX" style normals (the green channel is inverted relative to the glTF standard).  Is there a bug tracker for that, or can you file that one?

**Comment by bghgary** [comment]
@emackey Yes, we know about this one. There are a few conformance issues with our products that we are working to fix.

**Comment by bghgary** [comment]
FYI, this is how I make sure BabylonJS is working as expected: https://www.babylonjs.com/demos/gltfnormals/

**Pull request merged**
