### PR TITLE
ToyCar improvements

### PR DESCRIPTION
**Pull request by echadwick-wayfair**
Material improvements were made for an upcoming tutorial about KHR_materials_clearcoat:
1. Ambient occlusion textures were re-created for better shadowing.
2. Car paint under the clearcoat was roughened and changed to partially metallic, to better showcase the improvement of adding a shiny clearcoat.
3. Screenshot and readme updated.
4. Missing bufferViewes were added.

Before (left) vs. after (right):
new-occlusion

### CODE REVIEW

**Comment by bghgary** [comment]
Why are the screenshots much darker than before?

It still looks bright when [loaded in the Babylon.js sandbox](https://sandbox.babylonjs.com/?assetUrl=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/6457160f266c5d7702a97ca6dd3efe6c301cb23c/2.0/ToyCar/glTF/ToyCar.gltf). Did you capture the screenshot with something else?

**Comment by echadwick-wayfair** [comment]
I couldn't recall which renderer I used last time, and it's not called out in the readme, so I used the glTF Sample Viewer.

**Comment by bghgary** [comment]
Maybe indicate the renderer used for the screenshot in the readme?

**Comment by bghgary** [comment]
The IBL settings are probably different.

**Review by bghgary — APPROVED** [review]
LGTM. Anyone else want to review?

**Comment by cx20** [comment]
For reference, I tested this model with [gltf-test](https://github.com/cx20/gltf-test). Image thumbnails are links to each viewer.
I think that the effect of Ambient occlusion textures is different for each viewer. I don't know if that was the intended result.

|Library|before|after|
|:----:|:----:|:----:|
|three.js|[image](https://rawcdn.githack.com/cx20/gltf-test/006434aa92eb7d70f89328714a522369f12ccd05/examples/threejs/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)|[image](https://rawcdn.githack.com/cx20/gltf-test/393b378a9bd7062e6dc569ec78929f5c895d7af2/examples/threejs/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)|
|Babylon.js|[image](https://rawcdn.githack.com/cx20/gltf-test/006434aa92eb7d70f89328714a522369f12ccd05/examples/babylonjs/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)|[image](https://rawcdn.githack.com/cx20/gltf-test/393b378a9bd7062e6dc569ec78929f5c895d7af2/examples/babylonjs/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)|
|Filament|[image](https://rawcdn.githack.com/cx20/gltf-test/006434aa92eb7d70f89328714a522369f12ccd05/examples/filament/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)|[image](https://rawcdn.githack.com/cx20/gltf-test/393b378a9bd7062e6dc569ec78929f5c895d7af2/examples/filament/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)|
|PlayCanvas|[image](https://rawcdn.githack.com/cx20/gltf-test/006434aa92eb7d70f89328714a522369f12ccd05/examples/playcanvas/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)|[image](https://rawcdn.githack.com/cx20/gltf-test/393b378a9bd7062e6dc569ec78929f5c895d7af2/examples/playcanvas/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)|

**Comment by cx20** [comment]
PlayCanvas team has added ambient occlusion support to sheen, according to a tweet.
https://twitter.com/GustavSterbrant/status/1630988440408866816

I will update the test results when new version is released.

**Pull request merged**
