### PR TITLE
StainedGlassLamp model

### PR DESCRIPTION
**Pull request by echadwick-wayfair**
An example model to test and demonstrate KHR_materials_clearcoat,  KHR_materials_ior, KHR_materials_translucency, KHR_materials_transmission, KHR_materials_variants, KHR_materials_volume, and KHR_texture_basisu.

Re-posting [#288](https://github.com/KhronosGroup/glTF-Sample-Models/pull/288) into its own branch, with slight updates, and including the source model.

screenshot_large

### CODE REVIEW

**Comment by cx20** [comment]
I think this model is very nice. However, I am worried about the bloated repository size.
The average size of the folders in the other sample models is 12-13MB, so this model is much larger than that.

|Folder Name                            |  Folder Size   |
|:--------------------------------------|--------:|
|2.0/StainedGlassLamp/glTF              |  29.3 MB|
|2.0/StainedGlassLamp/glTF-Binary       |  29.3 MB|
|2.0/StainedGlassLamp/glTF-KTX          |  13.2 MB|
|2.0/StainedGlassLamp/glTF-Translucency |  27.5 MB|
|2.0/StainedGlassLamp/glTF-Variants     |  29.4 MB|
|2.0/StainedGlassLamp/screenshot        |   3.4 MB|
|sourceModels/StainedGlassLamp          |  60.5 MB|
|                                 Total | 192.6 MB|

**Comment by echadwick-wayfair** [comment]
Thanks for this. A few ideas:

1. Should I compress each folder with KTX, then remove the redundant \glTF-KTX ?
1. Should we keep the textures in sourceModels as PNG files?
1. Should I replace the (larger) .Max model in sourceModels with FBX or OBJ (smaller file)?
1. Should down-sample the PNGs in sourceModels to match the image sizes used in the glTFs? These are mostly 2048 PNGs.
1. Should I remove any of the model versions?

**Comment by lexaknyazev** [comment]
> Should I compress each folder with KTX, then remove the redundant \glTF-KTX ?

No, since people implementing new PBR extensions may lack KTX support.

> Should we keep the textures in sourceModels as PNG files?

Yes.

> Should I replace the (larger) .Max model in sourceModels with FBX or OBJ (smaller file)?

The `sourceModels` asset should contain proper materials, so OBJ is probably not an option.

> Should down-sample the PNGs in sourceModels to match the image sizes used in the glTFs? These are mostly 2048 PNGs.

This repo has lots of 2048 PNGs, so it should be fine. In fact, it may be even better to use the same PNGs (if possible) for source models and glTFs so that git could deduplicate them internally.

> Should I remove any of the model versions?

In my opinion, the GLB version doesn't add much value to this sample model.

---

Also please remove the validation info from the readme since that'll change eventually.

**Comment by cx20** [comment]
> 5. Should I remove any of the model versions?

I compared each model with `Babylon.js`. It looks the same as `glTF` / `glTF-Binary` / `glTF-KTX` / `glTF-Variants (Lamp on)`.
What about the idea of removing the same looking `glTF` / `glTF-Binary` and promoting `glTF-Variants` to `glTF`?
If we remove the two variations, we save 60 MB.

||||
|:---:|:---:|:---:|
|[image](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://rawcdn.githack.com/KhronosGroup/glTF-Sample-Models/de58574a5f183e6b15b9840f50d7be7006704d86/2.0/StainedGlassLamp/glTF/StainedGlassLamp.gltf&scale=3)|[image](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://rawcdn.githack.com/KhronosGroup/glTF-Sample-Models/de58574a5f183e6b15b9840f50d7be7006704d86/2.0/StainedGlassLamp/glTF-Binary/StainedGlassLamp.glb&scale=3)|[image](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://rawcdn.githack.com/KhronosGroup/glTF-Sample-Models/de58574a5f183e6b15b9840f50d7be7006704d86/2.0/StainedGlassLamp/glTF-KTX/StainedGlassLamp_ktx.gltf&scale=3)|
|[image](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://rawcdn.githack.com/KhronosGroup/glTF-Sample-Models/de58574a5f183e6b15b9840f50d7be7006704d86/2.0/StainedGlassLamp/glTF-Translucency/StainedGlassLamp_Translucency.gltf&scale=3)|[image](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://rawcdn.githack.com/KhronosGroup/glTF-Sample-Models/de58574a5f183e6b15b9840f50d7be7006704d86/2.0/StainedGlassLamp/glTF-Variants/StainedGlassLamp_Variants.gltf&scale=3)|[image](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://rawcdn.githack.com/KhronosGroup/glTF-Sample-Models/de58574a5f183e6b15b9840f50d7be7006704d86/2.0/StainedGlassLamp/glTF-Variants/StainedGlassLamp_Variants.gltf&scale=3)|

I will link to the following issue as a related topic.
https://github.com/KhronosGroup/glTF-Sample-Models/issues/272

**Comment by cx20** [comment]
@echadwick-wayfair Thank you for organizing the folder of models.

Is it possible to change the folder name to `glTF-BasisU` instead of `glTF-KTX`?
The reason for this is that the folder name for the `KHR_texture_basisu` version of `FlightHelmet` is `glTF-BasisU`.
See: https://github.com/KhronosGroup/glTF-Sample-Models/pull/285

And if possible, To be consistent with other samples, it is better to name the sample model file the same as the folder name is a good idea.

|Folder Name     |File Name|
|:---------------|:--------|
|`Duck`/glTF       |`Duck`.gltf|
|`Duck`/glTF-Binary|`Duck`.glb |

|Folder Name     |File Name|
|:----|:-----|
|`StainedGlassLamp`/glTF|`StainedGlassLamp`.gltf|
|`StainedGlassLamp`/glTF-JPG-PNG|`StainedGlassLamp`.gltf|
|`StainedGlassLamp`/glTF-BasisU|`StainedGlassLamp`.gltf|

**Comment by rsahlin** [comment]
> Is it possible to change the folder name to `glTF-BasisU` instead of `glTF-KTX`?
> The reason for this is that the folder name for the `KHR_texture_basisu` version of `FlightHelmet` is `glTF-BasisU`.
> See: #285
> 

Hi @cx20  and thanks for your comments.
I think we should think about this for a moment.
As I understand we should start using KTX2 (or simply KTX) when referring to 'supercompressed' (BasisU) assets.
This is so that we have a consistent way of communicating.

I know that the extension that adds the support for supercompressed textures is called _KHR_texture_basisu_ but the carrier is KTX (version 2)

**Comment by cx20** [comment]
@rsahlin Thanks for letting me know about your concerns.
I'm not too particular about the folder name `glTF-BasisU`. I simply suggested it as a way to make folders with similar meanings more consistent in the repository.

@bghgary Do you have any advice on folder names for this model?

**Comment by bghgary** [comment]
> As I understand we should start using KTX2 (or simply KTX) when referring to 'supercompressed' (BasisU) assets.

Hmm, I haven't heard this. KTX files are not necessarily supercompressed BasisU files.

I would recommend calling it glTF-BasisU.

**Comment by cx20** [comment]
For reference, I have listed the names currently used for glTF folders. So far, `glTF-JPG-PNG` and` glTF-KTX` have not been used.

`glTF`
`glTF-BasisU`
`glTF-Binary`
`glTF-Draco`
`glTF-Embedded`
`glTF-Embedded-buffer`
`glTF-IBL`
`glTF-pbrSpecularGlossiness`
`glTF-Quantized`

(I don't think there will be any significant impact by increasing the folder name. The only impact would be that I would have to add a few more `if` statements when I use [gltf-test](https://cx20.github.io/gltf-test/) to display it.)

image

**Comment by rsahlin** [comment]
> I would recommend calling it glTF-BasisU.

What would the drawback be with calling it glTF-KTX2?

From a broader ecosystem perspective I think it makes sense to try to unify how we name our features.
I know that historically we usually use the technical name of the feature.
In this case,  to make it easier for the rest of the ecosystem to understand I think we should consider using KTX2 instead of BasisU.

**Comment by lexaknyazev** [comment]
- The glTF extension is called `KHR_texture_basisu`.
- KTX v2 can handle much more payload formats than just Basis Universal supercompression.
- There will be other KTX use cases within glTF.

That said, we could use `glTF-KTX-BasisU` to give the most precise context possible.

**Comment by emackey** [comment]
Once the folder name is settled (and it looks like it is, from @lexaknyazev's comment above), we should update the files here and in other PRs that offer KTX, such as #285.

**Comment by echadwick-wayfair** [comment]
I noticed KTX2 model has some problems:
- The glTF is missing extensionsUsed and extensionsRequired
- The model doesn't finish loading in https://modelviewer.dev/examples/tester.html
- glTF Sample Viewer can't load the model either:
image
image

I'm re-compressing the textures to see if this fixes the problems.

**Comment by echadwick-wayfair** [comment]
Ah it was missing the extension definitions in the Textures section!
image

I'll submit a fix soon.

**Comment by bghgary** [comment]
Somewhat minor, but there is a seam on the lamp. It appears in at least in the bump normal, roughness, metallic maps also. Not sure what's causing it.

image

**Review by echadwick-wayfair — COMMENTED** [review]
The pathtracer version created for dsPBR use is actually in a separate commit, see https://github.com/KhronosGroup/3D-Formats-Guidelines/tree/main/samples/StainedGlassLamp

**Comment by cx20** [comment]
@echadwick-wayfair  

I tried the latest version of the model locally.
However, `Lamp on` is not displayed in Variants. Is this the intended change? I think it was displayed before.

```json
"extensions": {
"KHR_materials_variants": {
    "variants": [
        {
            "name": "Lamp off"
        }
    ]
}
```

**Comment by echadwick-wayfair** [comment]
Thanks for the review. Yes that is intended. It seems to me the "lamp on" variant is redundant since it's a duplicate of the original state.

**Comment by cx20** [comment]
> Thanks for the review. Yes that is intended. It seems to me the "lamp on" variant is redundant since it's a duplicate of the original state.

I see, it is the same idea as the default camera.
I will have to modify the example program because I have not taken into account the default state of variants in the [gltf-test](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=StainedGlassLamp&scale=3&type=glTF).
Currently, gltf-test just shows the list in the extension in variants.

image

**Comment by echadwick-wayfair** [comment]
Is there anything else that needs to be done with this asset to resolve the merge? Thanks.

**Comment by emackey** [comment]
The choice between "Lamp off" vs "default" seems far less intuitive than the old "Lamp off" vs "Lamp on".  I think the KHR_material_variants spec itself needs a bit of clarification.  Perhaps we can give the default state a name somehow, or ask clients to detect whether the default state is redundant with the named states and simply not show it when it's redundant.  Or we could ask implementors of variants to always include the default state among the variants, and say that clients are not required to offer the default state, and should instead detect its name from matching it to the list of named states or something.

It seems like something that needs discussion at the spec level before we commit to a model like this one that forces clients to show a nameless state.

**Comment by emackey** [comment]
Thanks again @echadwick-wayfair for this amazing model!

**Pull request merged**
