### PR TITLE
Update/add source models (Avocado, BarramundiFish, BoomBox, Corset, and Lantern)

### PR DESCRIPTION
**Pull request by bghgary**
#51

### CODE REVIEW

**Comment by emackey** [comment]
`sourceModels/Lantern/T_LanternPole_mr.png` looks odd to me.  Is it a metal/rough map?  There's not supposed to be an alpha channel in that map is there?

**Comment by bghgary** [comment]
That's a metallic smoothness texture intended for Unity3D which uses a sRGB grayscale metallic in RGB and a linear smoothness in A.

**Comment by emackey** [comment]
Oh, Unity, right.  Thanks.

**Comment by lexaknyazev** [comment]
Please update glTF versions of Avocado and BarramundiFish to this PR. These models in `master` (https://github.com/KhronosGroup/glTF-Sample-Models/commit/ef49777e5e63632b089b238bffe4515dbe8e1325) were produced by collada2gltf from now removed `.dae`s.

**Comment by pjcozzi** [comment]
@bghgary please squash commits before merging to keep the repo size down.

**Comment by bghgary** [comment]
@pjcozzi will do.

**Comment by bghgary** [comment]
@lexaknyazev I've updated the models.

@pjcozzi I was thinking whoever does the merge will squash the changes using GitHub. Is that good enough or did you mean something else?

**Comment by pjcozzi** [comment]
> @pjcozzi I was thinking whoever does the merge will squash the changes using GitHub. Is that good enough or did you mean something else?

Ah yes, I forgot about that feature!

@lexaknyazev please merge if you are happy with 2fb870b4ce7c373a0ccfb105caf00c90346f042a.

**Pull request merged**
