### PR TITLE
Update Draco gltf models using ratified bitstream

### PR DESCRIPTION
**Pull request by FrankGalligan**
Models were created from branch:
https://github.com/google/draco/tree/gltf_2.0_draco_extension

### CODE REVIEW

**Comment by FrankGalligan** [comment]
@donmccurdy Can you try these files? I might redo them with more compression later. But I just want to make sure they work for you.

**Comment by donmccurdy** [comment]
These are working with https://github.com/donmccurdy/three.js/pull/6, thanks 👍

**Comment by donmccurdy** [comment]
In [./javascript](https://github.com/google/draco/tree/gltf_2.0_draco_extension/javascript), should there be a glTF flavour of the encoder? Or are they the same?

**Comment by lexaknyazev** [comment]
@FrankGalligan 
Why do some attributes in GearboxAssy model point to an accessor with indices?
https://github.com/FrankGalligan/glTF-Sample-Models/blob/dae68f182050542e0551172ec8178b739493ff6b/2.0/GearboxAssy/glTF-Draco/GearboxAssy.gltf#L2431-L2436

This causes validation errors:
https://travis-ci.org/KhronosGroup/glTF-Sample-Models/builds/333954339#L883

**Comment by FrankGalligan** [comment]
@lexaknyazev filed https://github.com/FrankGalligan/gltf-pipeline/issues/1

**Comment by pjcozzi** [comment]
What's left before we can merge this?

**Comment by lexaknyazev** [comment]
How does this PR relate to #116?

**Comment by donmccurdy** [comment]
> How does this PR relate to #116?

Those models were created with a pre-spec version of the encoder. I believe this PR can replace #116.

**Comment by donmccurdy** [comment]
> What's left before we can merge this?

I've tested 4-5 of these in the three.js Draco implementation, and they looked good to me.

**Comment by pjcozzi** [comment]
Some of of these - and soon all - have also been tested with Cesium.  CC https://github.com/AnalyticalGraphicsInc/cesium/pull/6191

**Comment by bghgary** [comment]
The fallback attributes are not working for me. Looks like `bufferView` is missing from the accessors.

https://github.com/FrankGalligan/glTF-Sample-Models/blob/be470ea72ecb7adf2b30932349d1b12164af07b7/2.0/Box/glTF-Draco/Box.gltf#L47

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/accessor.schema.json#L11

**Comment by bghgary** [comment]
I just noticed that extensionsRequired is set for these. If the fallback buffers are intended to work, then this should be removed. If not, then the fallback buffers should be removed.

**Comment by donmccurdy** [comment]
I believe accessors with missing bufferviews is the expected Draco-required output.

**Comment by donmccurdy** [comment]
From the spec: 

> Then the loader must process `attributes` and `indices` properties of the `primitive`. When loading each `accessor`, you must ignore the `bufferView` and go to the previously decoded Draco geometry in the `primitive` to get the data of indices and attributes.

We implemented it this way in three.js:

```js
if ( accessorDef.bufferView === undefined && accessorDef.sparse === undefined ) {

  // Ignore empty accessors, which may be used to declare runtime
  // information about attributes coming from another source (e.g. Draco
  // compression extension).
  return null;

}
```

/cc @lexaknyazev

**Comment by bghgary** [comment]
Yes, sorry for my confusion. I reread the spec and I now understand what it is supposed to look like when the extension is required.

I think we can add a couple of minor things to avoid confusion.
* Add an short explanation to the extension required part in the spec and indicate that the only difference is that `buffer` is missing from the `bufferView`.
* Add a sample model of Draco with a fallback where Draco is only in `extensionsUsed`. We can also add this to the asset generator project instead if that's better.

**Comment by donmccurdy** [comment]
> Add an short explanation to the extension required part in the spec and indicate that the only difference is that bufferView is missing from the accessor.

+1 for adding the explanation. Let's do that after the PR is merged.

> Add a sample model of Draco with a fallback where Draco is only in extensionsUsed. We can also add this to the asset generator project instead if that's better.

Also +1. I tried to keep this case in mind with three.js implementation, but haven't tested it and would be surprised if it works yet.

**Comment by pjcozzi** [comment]
@bghgary @donmccurdy submitted https://github.com/KhronosGroup/glTF/issues/1244.

Please hit merge if this is otherwise ready. :rocket: :rocket: :rocket:

**Comment by bghgary** [comment]
I tried all the models with a glTF-Draco folder. All of them are working for me except:
* CesiumMan
* Monster
* RiggedFigure

Does this work for anyone else? It would be good to know if it's the model before I dig in to why.

**Comment by donmccurdy** [comment]
Those three are working for me, yes. See: https://github.com/mrdoob/three.js/pull/13194

**Comment by bghgary** [comment]
I think I figured it out, but would like confirmation. It looks like the unique ids are mapped wrong in RiggedFigure. I haven't checked the rest of them.

**Comment by bghgary** [comment]
The JOINTS_0 attribute is returning floats that are not integers.

```
0: 2.000000238418579
1: 3.0021979808807373
2: 4.000000476837158
3: 0
```

Is this expected?

**Comment by bghgary** [comment]
I fixed this issue from my end and all of the models are passing for me now. I am okay with merging if the JOINTS_0 issue is expected.

**Comment by donmccurdy** [comment]
Confirmed *Rigged Figure* is working in three.js, but as Gary mentions the joint indices are floats not ints yes.

**Comment by FrankGalligan** [comment]
I think the spec is fine as it should be int. Even the gltf for the draco version says the data should be int:
https://github.com/FrankGalligan/glTF-Sample-Models/blob/be470ea72ecb7adf2b30932349d1b12164af07b7/2.0/RiggedFigure/glTF-Draco/RiggedFigure.gltf#L2481

I think this is an implementation bug.

**Comment by donmccurdy** [comment]
Thanks all! Merging this, and we can address the JOINTS_0 implementation bug with a followup. Meanwhile, opened another issue here: https://github.com/KhronosGroup/glTF-Sample-Models/issues/147

**Pull request merged**
