### PR TITLE
Added sample models for Draco_mesh_compression_extension

### PR DESCRIPTION
**Pull request by fanzhanggoogle**
Hi,

This PR adds sample models for usage of [KHR_draco_geometry_compression](https://github.com/KhronosGroup/glTF/pull/874). These models are created using [COLLADA2GLTF](https://github.com/KhronosGroup/COLLADA2GLTF/pull/79). Please see the `glTF-Draco` folder in each model folder. The models could be loaded by modified [ThreeJS GLTF loader](https://github.com/fanzhanggoogle/gltf-test/tree/draco_2.0_1.0/libs/three.js/draco).

Here's preliminary compression result on the meshes of sample models:
### Comparison on geometries (mesh/primitive only)
| Model Name | Total Geometry Size (byte) | Compressed Size (byte) | Compression Ratio |
| ------------- | ------------- | ------------- | ------------- |
| 2CylinderEngine  | 1794612 | 183530 | 9.778303275 |
| Avocado | 23580  | 3988 | 5.912738215 | 
| BarramundiFish | 128208  | 17448 | 7.348005502 | 
| BoomBox | 207816  | 27651 | 7.515677552 | 
| Box | 648  | 160 | 4.05 | 
| BrainStem | 2009628 | 167491 | 11.9984 | 
| Buggy  | 7745988  | 692824 | 11.18031131 | 
| CesiumMan  | 211320  | 17535 | 12.05132592 | 
| CesiumMilkTruck  | 108144  | 14785 | 7.31444 | 
| Corset | 662184  | 83635 | 7.917546482 | 
| Duck  | 102040  | 11354 | 8.987141096 | 
| GearboxAssy  | 4915704  | 423307 | 11.61262157 | 
| Lantern | 231324  | 28535 | 8.106676012 | 
| Monster  | 48984  | 6664 | 7.350540216 | 
| ReciprocatingSaw  | 3496764 | 333415 | 10.48772251 | 
| RiggedFigure  | 19296  | 2830 | 6.81837 | 
| RiggedSimple  | 5736  | 772 | 7.430051813 | 
| VC  | 669786  | 152188 | 4.401043 | 
| WaterBottle | 149412  | 15146 | 9.864782781 | 

### Comparison on glTF files (including texture, gltf file and other data)
| Model Name | Uncompressed GLB File Size  (byte) | Compressed GLB File Size (byte) | Compression Ratio |
| ------------- | ------------- | ------------- | ------------- |
| 2CylinderEngine  | 1838084 | 230056 | 7.989724241 |
| Box | 1664  | 1240 | 1.341935484 | 
| BrainStem | 3195280 | 1357816 | 2.35324963 | 
| Buggy  | 7885636  | 845776 | 9.323551389 | 
| CesiumMan  | 491700  | 297696 | 1.65168494 | 
| CesiumMilkTruck  | 542172  | 449056 | 1.207359438 | 
| Duck  | 120484  | 29768 | 4.047433486 | 
| GearboxAssy  | 4958788  | 470248 | 10.54504857 | 
| Monster  | 327700  | 285204 | 1.149002118 | 
| ReciprocatingSaw  | 3562996 | 405476 | 8.787193323 | 
| RiggedFigure  | 50092  | 33416 | 1.499042375 | 
| RiggedSimple  | 11072  | 6004 | 1.844103931 | 
| VC  | 3086448  | 2584244 | 1.194333043 | 

For geometry part of data, the extension has a good compression ratio around 9X in average. But we are aware of that if comparing the entire glTF assets (e.g. in glTF-Binary format), the sizes of some models don't have significant reduction (in average ~3X compression). That's mainly because the animation data and texture image is a big part of some assets which the extension doesn't compress. We have plans to work on at least compressing the animation data as another extension in the near future.
Any feedback is very welcomed! Thank you!

@pjcozzi
@lexaknyazev
@FrankGalligan
@ondys
@donmccurdy 
@jbrettle
@bghgary
@zellski

### CODE REVIEW

**Comment by pjcozzi** [comment]
Really awesome, thanks @fanzhanggoogle!  This will be a big help to engine devs.

For the **Total Geometry Size (byte)** column, are these gzipped?

For the **Uncompressed GLB File Size (byte)** column, would it be better to report these numbers gzipped?  For texture-heavy models, they may not be much different since jpg will not gzip well.

Animation compression in the future will be amazing! :grinning: 

@bghgary let us know how tests go with BabylonJS.

**Comment by donmccurdy** [comment]
@fanzhanggoogle do these need to be regenerated with the specification version of the Draco encoder? I'm getting errors (`THREE.DRACOLoader: Decoding failed: Failed to decode geometry data.`) after updating to the `_gltf` versions of the decoder.

**Comment by FrankGalligan** [comment]
Hey Don,

I will update those models for you today. I was trying to get the animation
updated before, but I will do that first.

**Comment by FrankGalligan** [comment]
For posterity most of the files were compressed with these settings:
--draco.quantizePosition 10 --draco.quantizeNormal 8 --draco.quantizeTexcoord 8 --draco.quantizeColor 8 --draco.quantizeSkin 10

**Comment by bghgary** [comment]
Should we close this given #145 is now merged?

**Comment by donmccurdy** [comment]
> Should we close this given #145 is now merged?

👍

**Pull request closed without merging**
