### PR TITLE
RiggedSimple: remove no-op channels

### PR DESCRIPTION
**Pull request by andreasplesch**

### CODE REVIEW

**Comment by bghgary** [comment]
I'm don't think mucking with the JSON directly is a good idea. Now there will be part of the binary that isn't referenced and the [source model](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/sourceModels/RiggedSimple) is out of sync. I think we should either fix collada2gltf to not output these or use some automated tool like gltf-pipeline to clean it up.

**Comment by andreasplesch** [comment]
I think the source model is rather irrelevant. The collada data looks like it is actually not the original source but itself generated by an inefficient exporter itself. A main, perhaps the most important function of the sample models is that they can be inspected and learned from, with the knowledge that they are validated, and work with many glTF viewers and systems. It would be great if gltf-pipeline could be updated to recognize no-op animation channels or no-op/default translation, rotation, scale data.

**Comment by bghgary** [comment]
The source model is how some of these models are generated by running it through collada2gltf. If we make an update to collada2gltf or the source model and there are manual changes to the resulting gltf, we won't be able to run an automated script to generate these models anymore.

**Comment by emackey** [comment]
Fixes #86, Fixes #204 

@bghgary I'm on the fence about the need for future re-conversions of these models.  We do have a number of hand-made models, for example showing an individual triangle or box.  For more complex models, we now have at least one working glTF importer.  Do we really need to keep the Collada file around, and ensure that the provided sample can be automatically regenerated from it?

**Comment by emackey** [comment]
> Now there will be part of the binary that isn't referenced

That would be a problem, yes.

**Comment by bghgary** [comment]
> Do we really need to keep the Collada file around, and ensure that the provided sample can be automatically regenerated from it?

I don't have a strong preference, but if they are going to be out of sync, then we should remove the source.

**Comment by bghgary** [comment]
Or state in the source that manual modifications were made.

**Comment by andreasplesch** [comment]
I had added a step to the generator key value indicating manual modification. 

The .dae says it is exported from blender. It animates the full trafo matrix. Collada2gltf presumably could check during decomposition into  TRS if there is no change. Perhaps worth filing an issue with it.

If the .blend is available it may be easy to check how the blender exporter deals with it.

**Comment by emackey** [comment]
Thanks @andreasplesch.  This model was rebuilt in #245.

In general, I think we should prefer fixing the conversion/export toolchain as opposed to manually fixing samples with hand-edits (except for just those few samples that were created by hand, which this one is not).

**Comment by andreasplesch** [comment]
ok, this should rather be fixed here: https://github.com/KhronosGroup/COLLADA2GLTF/issues/225.
#86 tracks that also.

**Pull request closed without merging**
