### PR TITLE
Update sheen cloth textures from 16-bit to 8-bit

### PR DESCRIPTION
**Pull request by bghgary**
I noticed this while debugging some code. There is no reason why these textures need to be 16-bit.

See https://github.com/KhronosGroup/glTF/issues/1561 for a discussion on 16-bit texture support.

### CODE REVIEW

**Comment by cx20** [comment]
BTW, Perhaps this should be reported as a separate issue, but there seems to be a difference in display results between Babylon.js `v5.0.0 alpha.3` and `v5.0.0 alpha.30`.
I think the screenshots of this model were taken with an early version of Babylon.js v5.0.
I can't judge what is correct, but if the results displayed by the latest version of Babylon.js are more accurate, then I suggest you update the screenshot as well.

|library|IBL|result|
|:-----:|:-----:|:-----:|
|[README's screenshot](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SheenCloth)||image|
|[Babylon.js v5.0.0-alpha.3](https://rawcdn.githack.com/cx20/gltf-test/f23668f155066b1eefaeb1f0144b5319d92e1df9/examples/babylonjs/index.html?url=https://rawcdn.githack.com/bghgary/glTF-Sample-Models/6f6b1639c5377d6c2cd52ba20e99bec44c2e4ff8/2.0/SheenCloth/glTF/SheenCloth.gltf&scale=50)|papermill|image|
|[Babylon.js v5.0.0-alpha.30](https://rawcdn.githack.com/cx20/gltf-test/cd4461374bfa3f2ca6b94307de33eb839bd4952d/examples/babylonjs/index.html?url=https://rawcdn.githack.com/bghgary/glTF-Sample-Models/6f6b1639c5377d6c2cd52ba20e99bec44c2e4ff8/2.0/SheenCloth/glTF/SheenCloth.gltf&scale=50)|papermill|image|

For reference, `Filament` has the following results.
|Library|IBL|result|
|:-----:|:----:|:----:|
|Filament v1.10.5 + ToneMapping default|papermill|image|
|[Filament v1.10.5 + ToneMapping.LINEAR](https://rawcdn.githack.com/cx20/gltf-test/cd4461374bfa3f2ca6b94307de33eb839bd4952d/examples/filament/index.html?url=https://rawcdn.githack.com/bghgary/glTF-Sample-Models/6f6b1639c5377d6c2cd52ba20e99bec44c2e4ff8/2.0/SheenCloth/glTF/SheenCloth.gltf&scale=50)|papermill|image|

**Comment by bghgary** [comment]
> there seems to be a difference in display results between Babylon.js v5.0.0 alpha.3 and v5.0.0 alpha.30.

I believe this is caused by [this fix](https://github.com/BabylonJS/Babylon.js/issues/10360) which more accurately interpolates between colors. I'll double check.

**Comment by bghgary** [comment]
The sheen color being different after the change was a bug. We've fixed it here: https://github.com/BabylonJS/Babylon.js/pull/10696/files?short_path=eade1a1#diff-eade1a1ebbbda0b0f102a91395a1cd6d9d0e908b745c2ebc6cf1193448723596

**Comment by cx20** [comment]
@bghgary Thank you for your confirmation. I tried viewing again with the latest build of Babylon.js.
It is difficult for me to judge whether the result is correct or not, but it is close to the result of enabling `KHR_materials_sheen` extension in the glTF Sample Viewer, so I think the extension is probably working correctly.

|library|result|
|:-----:|:-----:|
|[Babylon.js v5.0.0-alpha.30](https://rawcdn.githack.com/cx20/gltf-test/cd4461374bfa3f2ca6b94307de33eb839bd4952d/examples/babylonjs/index.html?url=https://rawcdn.githack.com/bghgary/glTF-Sample-Models/6f6b1639c5377d6c2cd52ba20e99bec44c2e4ff8/2.0/SheenCloth/glTF/SheenCloth.gltf&scale=50)|[image](https://rawcdn.githack.com/cx20/gltf-test/cd4461374bfa3f2ca6b94307de33eb839bd4952d/examples/babylonjs/index.html?url=https://rawcdn.githack.com/bghgary/glTF-Sample-Models/6f6b1639c5377d6c2cd52ba20e99bec44c2e4ff8/2.0/SheenCloth/glTF/SheenCloth.gltf&scale=50)|
|[Babylon.js v5.0.0-alpha.32](https://rawcdn.githack.com/cx20/gltf-test/4d9e8a7a7875481881d8defd49f6486d33e7ce4c/examples/babylonjs/index.html?category=tutorialModels&model=SheenCloth&scale=50&type=glTF)|[image](https://rawcdn.githack.com/cx20/gltf-test/4d9e8a7a7875481881d8defd49f6486d33e7ce4c/examples/babylonjs/index.html?category=tutorialModels&model=SheenCloth&scale=50&type=glTF)|
|glTF Sample Viewer (KHR_materials_sheen on)|image|
|glTF Sample Viewer (KHR_materials_sheen off)|image|

**Comment by bghgary** [comment]
> @bghgary Is it possible that a similar bug affects KHR_materials_specular? We saw a report of that recently, with the "SpecularTest" model in Babylon.

There was a fix in specular as well, so probably. Can you point me to the issue?

**Comment by emackey** [comment]
> There was a fix in specular as well, so probably. Can you point me to the issue?

@bghgary It was a TSG email on July 16 with the subject "Colorspace conversions in the new Specular Test model"  I didn't verify everything written there, but it does look like the SpecularTest model has slight differences between factors & textures now.

**Comment by bghgary** [comment]
> @bghgary It was a TSG email on July 16 with the subject "Colorspace conversions in the new Specular Test model" I didn't verify everything written there, but it does look like the SpecularTest model has slight differences between factors & textures now.

I confirmed this was broken and is now fixed. I'll reply to the TSG email also.

**Pull request merged**
