### PR TITLE
Adding "Mosquito In Amber" glTF sample of IOR, Transmission and Volume PBR extensions

### PR DESCRIPTION
**Pull request by wallabyway**
Adding glTF sample 3D model of a "Mosquito In Amber" that demostrates the IOR, KHR-materials-transmission and Volume PBR extensions, to add reflection and refraction to translucent materials.

See Press Announcement for more details: https://www.khronos.org/news/press/new-gltf-extensions-raise-the-bar-on-3d-asset-visual-realism

Model by Loïc Norgeot and mosquito scan by Geoffrey Marchal for Sketchfab licensed under CC BY 4.0

Title: "Real-time Refraction Demo: Mosquito in Amber"
Author: Sketchfab
License: CC-BY-4.0
Source: real-time-refraction-demo-mosquito-in-amber-37233d6ed84844fea1ebe88069ea58d1
Generator: "Sketchfab-7.51.0, hand-edited to add additional PBR glTF extensions."

### CODE REVIEW

**Comment by cx20** [comment]
For reference, I tried to display it in each library.

|Library|MosquitoInAmber.gltf - front|MosquitoInAmber.gltf - another angle|
|:--------:|:--------:|:--------:|
|[glTF Sample Viewer](https://github.khronos.org/glTF-Sample-Viewer-Release/)|image|image|
|[Three.js](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=MosquitoInAmber&scale=30&type=glTF)|image|image|
|[Babylon.js](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=MosquitoInAmber&scale=30&type=glTF)|image|image|
|[Filament](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=MosquitoInAmber&scale=30&type=glTF)|image|image|

**Comment by cx20** [comment]
I even tried to display the same model as above with the [Dassault Systèmes Enterprise PBR Sample Renderer](https://dassaultsystemes-technology.github.io/dspbr-pt/).
However, it is almost opaque and the mosquitoes in the amber do not seem to be visible. Is this the expected result?

|Library|MosquitoInAmber.gltf - front|MosquitoInAmber.gltf - another angle|
|:--------:|:--------:|:--------:|
|[Dassault path-tracer](https://dassaultsystemes-technology.github.io/dspbr-pt/)|image|image|

**Comment by wallabyway** [comment]
Three, Babylon agree with ref-viewer.   
@cx20 - Thank you for testing Filament and Dassault PT - I did not test those, but there looks to be a problem.
(I guess that's why we need to diversify the samples)

Next steps: We should get feedback from Filament and Dassault, to understand if the problem is on their end or on the ref-viewer side, before approving this PR.

Sound right?

**Comment by cx20** [comment]
I don't know the technical details, but this may be a problem related to #324.

**Comment by emackey** [comment]
Thanks @wallabyway and @cx20!

**Pull request merged**
