### PR TITLE
SheenChair sample model updates

### PR DESCRIPTION
**Pull request by echadwick-wayfair**
- Re-formatted the glTF to the current Sheen spec ( https://github.com/KhronosGroup/glTF/blob/971ff4d74c4f34640b6c19c8bba07d0e3b1ccff8/extensions/2.0/Khronos/KHR_materials_sheen/README.md).
- Added a readme and screenshots.

### CODE REVIEW

**Comment by cx20** [comment]
To be consistent with other samples, it is better to name the sample model file the same as the folder name is a good idea.

|Folder Name     |File Name|
|:---------------|:--------|
|`Duck`/glTF       |`Duck`.gltf|
|`Duck`/glTF-Binary|`Duck`.glb |

**Comment by echadwick-wayfair** [comment]
Is it preferred to use PascalCase or can the assets be all lowercase?

**Comment by cx20** [comment]
@echadwick-wayfair So far, I think all the other samples are in `PascalCase` format. 
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/model-index.json

And please prepare a `screenshot` to go with the model. I am referring to the screenshots when listing with [gltf-test](https://github.com/cx20/gltf-test) etc.

**Comment by echadwick-wayfair** [comment]
OK thanks, I'll make sure it's PascalCase. 

Yes, I'm preparing a readme with a main screenshot plus a few additional images showing expected behavior. Just learning about how Git works so I can make a proper pull request.

**Comment by cx20** [comment]
@echadwick-wayfair This PR looks like a PR from `pbr-next` to `master`.
`SheenChair` If it's an update to the sample model, I think it's a good idea to send out a PR to `pbr-next`.

@UX3D-nopper Do you have any advice?

**Comment by UX3D-nopper** [comment]
Any pbr-next examples should go into pbr-next, as master contains should only contain examples with glTF 2.0 plus ratified extensions e.g. the latest clearcoat.

**Comment by echadwick-wayfair** [comment]
Sorry, I'm new to GitHub terminology & workflow. How do I cancel this pull request? I will start again via a fork of pbr-next.

**Comment by UX3D-nopper** [comment]
Just did it :-)

**Pull request closed without merging**
