### PR TITLE
Sample models for KHR_materials_variants extension

### PR DESCRIPTION
**Pull request by pushmatrix**
These are sample models for the KHR_materials_variants extension defined in https://github.com/KhronosGroup/glTF/pull/1681

I've included the separate variant models alongside the model that has all variants packed into it. I included those separate ones in case authoring tools want to test the extension.

I wasn't sure whether to put all these models in the root 2.0 folder, or to put them in their own KHRMaterialsVariants folder.

### CODE REVIEW

**Comment by cx20** [comment]
> I wasn't sure whether to put all these models in the root 2.0 folder, or to put them in their own KHRMaterialsVariants folder.

My personal opinion is that it is better to place the model in root to match the existing folder configuration.
Also, I think it's better to match the folder name with the file name.

|Folder Name     |File Name|
|:---------------|:--------|
|`Duck`/glTF       |`Duck`.gltf|
|`Duck`/glTF-Binary|`Duck`.glb |

Here are the proposed changes.

|before|after|
|:-----|:-----|
|2.0/KHRMaterialsVariants/`chairs`/glTF/`chairs`.gltf               |2.0/`MaterialsVariantsChairs`/glTF/`MaterialsVariantsChairs`.gltf      |
|2.0/KHRMaterialsVariants/`chairs`/glTF-Binary/`chairs`.glb         |2.0/`MaterialsVariantsChairs`/glTF-Binary/`MaterialsVariantsChairs`.glb|
|2.0/KHRMaterialsVariants/`chairs`/screenshot/`chairs`.jpg          |2.0/`MaterialsVariantsChairs`/screenshot/`screenshot`.jpg              |
|2.0/KHRMaterialsVariants/`helmet`/glTF/`helmet_combined`.gltf      |2.0/`MaterialsVariantsHelmet`/glTF/`MaterialsVariantsHelmet`.gltf      |
|2.0/KHRMaterialsVariants/`helmet`/glTF-Binary/`helmet_combined`.glb|2.0/`MaterialsVariantsHelmet`/glTF-Binary/`MaterialsVariantsHelmet`.glb|
|2.0/KHRMaterialsVariants/`shoes`/glTF/`shoes`.gltf                 |2.0/`MaterialsVariantsShoes`/glTF/`MaterialsVariantsShoes`.gltf        |
|2.0/KHRMaterialsVariants/`shoes`/glTF-Binary/`shoes`.glb           |2.0/`MaterialsVariantsShoes`/glTF-Binary/`MaterialsVariantsShoes`.glb  |

There are a few different colored models in the folder, but I don't think you should put them in this repository if you mean the assumed results. This repository is already close to 1GB, and it's better to keep the model to a minimum.

**Comment by pushmatrix** [comment]
Thanks @cx20 and @emackey. I've made those changes.

The helmet example was just to show that it's not just for digital commerce. It can be for games too. That's fine, I removed it and we can keep that for a blog post marketing the extension.

However, I want to keep the chair in there. Whereas the shoes are simplistic (only change base texture on 1 mesh), the chair represents a common ecommerce usecase where you have multiple pieces (in this case fabric & chair legs), and they can be configured differently. 2x fabric options and 2x wood bases make for 4 possible variants. This shows how you'd use the extension to represent that.

**Comment by cx20** [comment]
@pushmatrix Thank you for the change.

Please make one more change. Place the thumbnail image used to list the samples in the screenshot folder with the file name `screenshot/screenshot.<jpg|png|gif>`.

@emackey Are there any rules for adding models to the list page? Which category should we add it to, etc.
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/README.md
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/model-index.json

**Comment by pushmatrix** [comment]
@cx20 done and done 👍

**Comment by emackey** [comment]
@cx20 I've been wondering about organization lately.  Thoughts welcome on #272.

**Comment by cx20** [comment]
BTW, When I was checking this model in [gltf-vscode](https://github.com/AnalyticalGraphicsInc/gltf-vscode), I noticed that the Mesh data was stored in `base64`.
Perhaps you can reduce the size of the Mesh data file by some percentage by making it an external file in bin format.

```json
"buffers": [
  {
    "name": "shoes-processed",
    "byteLength": 705680,
    "uri": "data:application/octet-stream;base64,aogOP6tfKT+SlAA/yHslPzkPIz98D...
```

image

**Comment by emackey** [comment]
[Off-topic comment] Oh no, what happened with the Three.js button sticking off the edge like that in VSCode?  It doesn't look like that on my screens, I wonder how I can reproduce that...?

**Comment by cx20** [comment]
@emackey I have reported issues individually for gltf-vscode.
https://github.com/AnalyticalGraphicsInc/gltf-vscode/issues/190

**Comment by cx20** [comment]
I experimentally added this model to [gltf-test](https://cx20.github.io/gltf-test/) and confirmed that I can change the Variant in Babylon.js.

|variant|image|
|:---------:|:---------:|
|midnight|[image](https://rawcdn.githack.com/cx20/gltf-test/a28a0f78b7e06ed2a82f7b46f9521402ec7deb45/examples/babylonjs/index.html?category=tutorialModels&model=MaterialsVariantsShoe&scale=10&type=glTF)|
|street|[image](https://rawcdn.githack.com/cx20/gltf-test/a28a0f78b7e06ed2a82f7b46f9521402ec7deb45/examples/babylonjs/index.html?category=tutorialModels&model=MaterialsVariantsShoe&scale=10&type=glTF)|

**Comment by cx20** [comment]
I've confirmed that this extension works in three.js as well. See [gltf-test](https://github.com/cx20/gltf-test) for a [sample code](https://github.com/cx20/gltf-test/blob/b83be37de4505c57f899fbd4c69d82ce7aa38651/examples/threejs/index.js#L247-L268) to display it.
The following is an example display in three.js.

|variant|image|
|:----:|:----:|
|[midnight](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=MaterialsVariantsShoe&scale=10&type=glTF&variant=midnight)|[image](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=MaterialsVariantsShoe&scale=10&type=glTF&variant=midnight)|
|[street](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=MaterialsVariantsShoe&scale=10&type=glTF&variant=street)|[image](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=MaterialsVariantsShoe&scale=10&type=glTF&variant=street)|

image

**Comment by emackey** [comment]
Thanks again @pushmatrix, this is finally merged.

**Comment by pragneshmali99** [comment]
Respected Sir, 

How can i add "FB_material_variants" in gltf model json using THREE js GLTFLoader ?

Thanks & Regards,
Pragnesh Mali 
email: pragneshmali99@gmail.com

**Comment by emackey** [comment]
Hi @pragneshmali99, this issue tracker is not part of ThreeJS.  Please try asking on the ThreeJS forums or on StackOverflow or similar.  Thanks!

**Comment by Baldev007** [comment]
Hello @pushmatrix @cx20 @emackey 
I am a 3d artist and new here. and I don't know how to code. But I want to add this variant feature to my model. Can anyone tell me how to do it? I have variation texture and the gltf model.

**Comment by elalish** [comment]
@Baldev007 We're actually nearly done adding this feature to the model-viewer [editor](https://modelviewer.dev/editor/). Hopefully by next week you'll have a UI in the materials tab to create/select variants and load new textures.

**Comment by Baldev007** [comment]
> @Baldev007 We're actually nearly done adding this feature to the model-viewer [editor](https://modelviewer.dev/editor/). Hopefully by next week you'll have a UI in the materials tab to create/select variants and load new textures.

@elalish Hello, thanks for adding the variant feature in the model-viewer editor. but when I click on the download scene sometimes nothing happens. Do you guys know why it happens?

**Comment by elalish** [comment]
@Baldev007 No, feel free to open an issue on our Github: https://github.com/google/model-viewer/issues, but please give complete repro steps. Also, check for errors/warnings in the JS console.

**Pull request merged**
