### PR TITLE
Add TechniquesWebGLTest model

### PR DESCRIPTION
**Pull request by 06wj**
Add TechniquesWebGLTest model to test [`KHR_techniques_webgl`](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_techniques_webgl) extension.

[Hilo3d result:](https://hiloteam.github.io/Hilo3d/examples/glTFViewer/index.html?url=https://raw.githubusercontent.com/06wj/glTF-Sample-Models/KHR_techniques_webgl/2.0/TechniquesWebGLTest/glTF/TechniquesWebGLTest.gltf)
screenshot

### CODE REVIEW

**Comment by cx20** [comment]
@06wj Please change the file name of the model to be the same as the folder name.
`model.gltf` -> `TechniquesWebGLTest.gltf`

**Comment by cx20** [comment]
@06wj The title of [README.md](https://github.com/06wj/glTF-Sample-Models/blob/KHR_techniques_webgl/2.0/TechniquesWebGLTest/README.md) is `Unlit Test`. Is it correct?

**Comment by cx20** [comment]
I have added this test model experimentally to [gltf-test](https://github.com/cx20/gltf-test#extension-test-models). I think the current status is as follows.
image

**Comment by emackey** [comment]
@06wj Thanks for this test model.  Unfortunately `KHR_techniques_webgl` was never ratified, and it doesn't seem like the extension has consistent support, as shown in the gltf-test report shown above.  I think this extension was originally crafted as a means to import glTF 1.0 files to 2.0, but the need for that has been waning over the years.

I'm going to close this PR.  We'll keep this in mind in case there's renewed interest in it.

**Pull request closed without merging**
