### PR TITLE
Norbert's glTF 2.0 samples - using TANGENT4.

### PR DESCRIPTION
**Pull request by McNopper**

### CODE REVIEW

**Comment by bghgary** [comment]
> Using TANGENT4 as default now.
Think I got the math right (using http://crytek.com/download/izfrey_siggraph2011.pdf).

Sorry about this, I think we are not on the same page.

A couple of things:
1. TANGENT4 is not QTangent. It's tangent (XYZ) + handedness (-1 or 1).
2. What I meant was remove the tangents completely, but there is an issue here. We haven't defined the tangent math when they are not provided, so there is no way to generate a correct normal map right now.

Note: The models I submitted (BoomBox, Corset, and Lantern) do have normal maps but they don't have tangents. The normal maps use mikktspace (as they came from Unity), but as far as I'm aware, there isn't an easy way to calculate mikktspace at runtime. Thus, the normal map for these models will not render correctly in BabylonJS or ThreeJS as they both use a derivative-based tangent calculation in the shader. I'm working to figure out what a good standard way to calculate tangents at runtime. Once that's defined, then we can submit proper normal maps that work everywhere.

We have a couple of options:
1. Wait for the tangent math to be defined, don't specify tangents at all, and update the normal maps to match the math.
2. Commit these with TANGENT4 (tangent + handedness) but realize they will need to become option 1 later.
3. Submit just the models without normal maps for now and submit the models with normal maps later.

**Comment by McNopper** [comment]
Ah okay, did not know that. I had this discussion with these QTangents in mind,
I will go for option 2.
WIll do my changes,

**Comment by bghgary** [comment]
Looks good to me now.

**Comment by McNopper** [comment]
Oops, you were fast, Had no time to inform you :-)

**Comment by McNopper** [comment]
@pjcozzi Okay for you as well?

**Comment by pjcozzi** [comment]
Thanks @McNopper @bghgary!

**Pull request merged**
