### PR TITLE
Add flight helmet model

### PR DESCRIPTION
**Pull request by bghgary**
This is a high quality model from our tech artist @PatrickRyanMS. It is modeled after a real flight helmet and showcases what you can do with the core spec using PBR metallic roughness workflow.

### CODE REVIEW

**Comment by emackey** [comment]
This looks great!

Should we add a `glTF-Binary` flavor of this?  Lately it seems like GLB is the most important flavor of glTF to support.

**Comment by bghgary** [comment]
I didn't do this because of size. This asset is over 50MB and is by far the largest asset in the repo. Each flavor multiplies against this base size. There are also plenty of tools now that convert from glTF to GLB. Thoughts?

**Comment by emackey** [comment]
Hmm, OK.  SciFiHelmet also lacks a binary version, I guess we can have some models without it.

**Comment by cx20** [comment]
I tried this model with [gltf-test](https://github.com/cx20/gltf-test#pbr-models). 

The point I thought of as issue is as follows.
- The goggles of minimal-glTF-Loader are opaque.
- The goggles of PlayCanvas are opaque.
- The goggles of x3dom are transparent, but the contents displayed are different from other libraries.

Please tell me if there are other display parts different from the assumed one. I will report the issue to each library later.

The following is the execution result for each library. Khronos glTF Loader is excluded because `Too many texture` error appeared and it could not be displayed.

| | | |
|:-------:|:----------:|:----------:|
|[image](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=FlightHelmet&scale=0.5&type=glTF)|[image](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=FlightHelmet&scale=0.5&type=glTF)|[image](https://cx20.github.io/gltf-test/examples/cesium/index.html?category=tutorialModels&model=DamagedHelmet&scale=1.0&type=glTF)|
|[image](https://cx20.github.io/gltf-test/examples/grimoiregl/index.html?category=tutorialModels&model=FlightHelmet&scale=0.5&type=glTF)|[image](https://cx20.github.io/gltf-test/examples/xeogl/index.html?category=tutorialModels&model=FlightHelmet&scale=0.5&type=glTF)|[image](https://cx20.github.io/gltf-test/examples/minimal-gltf-loader/index.html?category=tutorialModels&model=FlightHelmet&scale=0.5&type=glTF)|
|[image](https://cx20.github.io/gltf-test/examples/claygl/index.html?category=tutorialModels&model=FlightHelmet&scale=0.5&type=glTF)|[image](https://cx20.github.io/gltf-test/examples/Hilo3d/index.html?category=tutorialModels&model=FlightHelmet&scale=0.5&type=glTF)|[image](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=FlightHelmet&scale=0.5&type=glTF)|
|[image](https://cx20.github.io/gltf-test/examples/x3dom/index.html?category=tutorialModels&model=FlightHelmet&scale=0.5&type=glTF)|||

**Comment by lexaknyazev** [comment]
@cx20 Please fix Cesium link, it shows DamagedHelmet.

**Comment by cx20** [comment]
@lexaknyazev Oops! I was linking to a different helmet. I fixed the link now.

**Comment by cx20** [comment]
I confirmed that the problem of goggles has been resolved by using the latest version library of PlayCanvas and x3dom.

|Three.js|PlayCanvas|x3dom|
|:-------:|:-----------:|:-------|
|image|image|image|

**Comment by donmccurdy** [comment]
Looks outstanding!

By the way, this helmet model contains a `TEXCOORD_1` attribute that appears to be unused.

**Comment by bghgary** [comment]
> By the way, this helmet model contains a `TEXCOORD_1` attribute that appears to be unused.

Yeah, I noticed this earlier too. I'm not sure where it's coming from since the source asset doesn't have it. I'll find out.

**Comment by bghgary** [comment]
Should be fixed with https://github.com/KhronosGroup/glTF-Sample-Models/pull/159

**Pull request merged**
