### PR TITLE
Update models compressed with Draco

### LINKED ISSUE #234: Some draco compressed models have invalid accessor count
I recently ran into the issue where the number of points coming back from `dracoGeometry.num_points()` did not match the value specified in `accessor.count`.

It seems that this is considered in the [spec](https://github.com/KhronosGroup/glTF/blob/1aae8e9084a5966c61f810dd3a3186fe084b642b/extensions/2.0/Khronos/KHR_draco_mesh_compression/README.md#implementation-note)
but some of the samples models are seemingly incorrect.

I see there is a related [issue](https://github.com/KhronosGroup/glTF-Sample-Models/issues/147) but it seems to be a bit more widespread than that one.

I discovered that the following models (glTF-Draco variants) appear to be incorrect:

- 2CylinderEngine
- BrainStem
- Buggy
- CesiumMan
- CesiumMilkTruck
- GearboxAssy
- Lantern
- Monster
- ReciprocatingSaw
- RiggedFigure
- VC

The issue I ran into was that my initial array buffers were not large enough to accept all of the values from the draco decoder. This results in very strange rendering with missing normals or positions.

My code (JS/WebGL) initializes all array buffers (and typed arrays) based on the accessor and it's not really feasible to resize after the decompression.

I have created a [gist](https://gist.github.com/shannon/5ecdb58d815bbe028348033dd0cbd6c4) that contains a breakdown of all the models and accessors where the counts don't match. As you can see, in some cases the descrepiency is rather large, in other cases the number of points returned from draco is less than the accessor count. In that case the result usually rendered ok but this means that I have much more memory allocated for the buffers than I need and wasted cycles on the draw.

Based on the discussion from #147 it seems that the exporters needed to be updated. That was quite a while ago so I don't know if it's already been done and these models just need to be updated.

### LINKED ISSUE #237: Mismatched accessor.count in Monster.gltf/glTF-Draco
image

### PR DESCRIPTION
**Pull request by FrankGalligan**
This PR fixes #234, #236, and #258. This PR would have also fixed #237,
but the Monster model has been removed, so #237 can be closed.

All of the modles were compressed with gltf-pipeline:
https://github.com/CesiumGS/gltf-pipeline

commit:
https://github.com/CesiumGS/gltf-pipeline/commit/16c8d08a7c39cc2dc39f15e281150d16e2419025

Command line:
gltf-pipeline.js -s -d  -i /KhronosGroup/glTF-Sample-Models/2.0/{INPUT_NAME}/glTF/{INPUT_NAME}.gltf -o /KhronosGroup/glTF-Sample-Models/2.0/{INPUT_NAME}/glTF-Draco/{INPUT_NAME}.gltf

Note: Some of the *.bin filenames changed as the behavior in
gltf-pipeline changed.

### CODE REVIEW

**Comment by emackey** [comment]
Frank, thanks so much for doing this.

I tested each of these models in VSCode, they all work in BabylonJS and Cesium.  Four of them wouldn't load in ThreeJS (inside VSCode) for me:

- CesiumMan
- BrainStem
- RiggedFigure
- RiggedSimple

These four gave me the following error:

```
TypeError: draco.DracoUInt16Array is not a constructor
```

But they seem to be OK in @donmccurdy's viewer, so I'm not sure what to make of that.  VSCode is still on r112 but I tried a custom build with r115 and it's not fixed.  It's not a showstopper if this is isolated to VSCode and doesn't affect the web, but I would like to track it down if possible.

Also I don't know why CI is taking so much time to respond to this branch.  Can anyone familiar with the CI here comment on that?

**Comment by lexaknyazev** [comment]
@emackey 
Maybe it's just a long queue. Travis had some scheduled maintenance today: https://www.traviscistatus.com/incidents/zyjqyg4w6x8v

**Comment by shannon** [comment]
FWIW, this does fix all the issues I had when I opened #234. This works well in my JS renderer.

However, I did notice that some were missing from was missing from the model-index.json.

- CesiumMan glTF-Draco
  https://github.com/FrankGalligan/glTF-Sample-Models/blob/update_models_with_draco/2.0/model-index.json#L183
- CesiumMilkTruck glTF-Draco
  https://github.com/FrankGalligan/glTF-Sample-Models/blob/update_models_with_draco/2.0/model-index.json#L192
- RiggedSimple glTF-Draco 
  https://github.com/FrankGalligan/glTF-Sample-Models/blob/update_models_with_draco/2.0/model-index.json#L380

**Comment by emackey** [comment]
@shannon Thanks for checking!

Don't worry to much about `model-index.json` for this PR.  There's a Python script here that regenerates it, and I can just run that on master once this gets merged.

**Comment by FrankGalligan** [comment]
Thanks for letting me know. I tried them in Babylon.js, three.js (Don
McCurdy's viewer) and also through the glTF Validator (no new issues).

Anyway the error is really weird. DracoUInt16Array has been in since
4/18/2018
https://github.com/google/draco/commit/4b2788bb5644c142c2801e7e27420f88abde0aff#diff-9b69a0b08084a56cbf7da393c77affb7

I will see if I can find what is going on.

**Comment by emackey** [comment]
@FrankGalligan False alarm.  I found some outdated Draco files bundled with the VSCode plugin.  Fixed in https://github.com/AnalyticalGraphicsInc/gltf-vscode/commit/c5cf446f75d6032b59184bc0b06967224cb72dde (but not published yet).

**Comment by FrankGalligan** [comment]
Awesome thanks!

**Pull request merged**
