### PR TITLE
Updates from validation

### PR DESCRIPTION
**Pull request by lasalvavida**
@lexaknyazev fixes for #59

### CODE REVIEW

**Comment by lexaknyazev** [comment]
@lasalvavida 
Great! Most issues are resolved. Remaining ones:
- `bufferView.byteStride` must be defined when two or more accessors use the same buffer view.
- `skin.joints` must be an array of nodes indices, `node.jointName` mustn't exist.

**Comment by lasalvavida** [comment]
> bufferView.byteStride must be defined when two or more accessors use the same buffer view.

One question here, the spec says:

> Buffer view could have byteStride property ... This field is defined only for buffer views that contain vertex attributes.

So, is this is only true for vertex attribute bufferViews correct? Is the intent here to have vertex attributes of different sizes split across multiple bufferViews such that they all have the same byteStride, or is it still acceptable to pack vertex attributes with different byte strides into a single bufferView with a declared byteStride of 0?

**Comment by lexaknyazev** [comment]
`byteStride` can't be `0`, so all accessors in a bufferView explicitly have the same byteStride.

**Comment by lasalvavida** [comment]
Okay, I'll update my implementation to match, just so you know the spec still says:

> bufferView.byteStride
> The stride, in bytes, between vertex attributes or other interleavable data. When this is zero, data is tightly packed.

**Comment by lasalvavida** [comment]
And the default value for byteStride is still listed as zero

**Comment by lexaknyazev** [comment]
Please, refer to JSON files for the most current properties definitions:
https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/bufferView.schema.json#L23-L31

The reference part of README.md is outdated.

**Comment by lasalvavida** [comment]
Updated

**Comment by lexaknyazev** [comment]
Couple more small tweaks:
- GLB versions mustn't contain `image.width/height`. There're no such fields in glTF 2.0.
- Default `node.matrix` value (identity matrix) should be omitted. E.g., see how it clutters **ReciprocatingSaw**.
- `camera.perspective.aspectRatio` can't be zero (see **VC** model).

**Comment by lasalvavida** [comment]
> camera.perspective.aspectRatio can't be zero (see VC model).

This actually comes from the COLLADA which appears to be incorrect. `aspect_ratio` is a required property if only a single `xfov` or `yfov` is present.

That being said, it looks like I can just omit this and it defaults to the canvas aspect ratio, correct?

**Comment by lexaknyazev** [comment]
> That being said, it looks like I can just omit this and it defaults to the canvas aspect ratio, correct?

Yes.

**Comment by lasalvavida** [comment]
Updated

**Comment by lexaknyazev** [comment]
@lasalvavida 
Were models updated after https://github.com/KhronosGroup/glTF-Sample-Models/issues/63#issuecomment-301344107 change? JSON's min/max values seem to be the same.

**Comment by lasalvavida** [comment]
Hmm... COLLADA2GLTF is using floats internally now where it was using doubles before; rapidjson doesn't have a write for float, only double, so maybe it has something to do with that. I'll look into it

**Comment by pjcozzi** [comment]
@lasalvavida - small request: please squash commits before this is merged to keep the repo size down, thanks!

**Comment by lexaknyazev** [comment]
Looks like ef89bd4032d5962920f9743eb5b1f6a9f5d33d1c accidentally removed many files from the tree.

@lasalvavida 
Could you please bring them back or just open a new PR with collada2gltf-only updates?

**Comment by lasalvavida** [comment]
Closed, continued in #67

**Pull request closed without merging**
