### PR TITLE
Add new model WalkingLady

### PR DESCRIPTION
**Pull request by emadurandal**
Hi, everyone.

I have been promoting glTF support with my WebGL library GLBoost.
I created my skinning animation model myself using Maya and tried playing it.

This time, pull requesting this model is for some interesting reasons.

Of course, the GLBoost library plays this model correctly. However, all other well-known WebGL libraries fail to play.

* [Cesium.js](http://jsdo.it/cx20/Mj2H)
* [Babylon.js](http://jsdo.it/cx20/WjrC)
* [Three.js](http://jsdo.it/cx20/27ll)

Is this model something special? No, JglTF seems to be able to play this model properly.

For this reason, I think that there are still some problems in implementations of skinning animation in each WebGL library.
This model may be a good touchstone in trying the compatibility of glTF skinning animation of each library.

If there is no problem, I am glad if you adopt it.

### Related Issues
https://github.com/KhronosGroup/glTF/issues/685
https://github.com/javagl/JglTF/issues/2

### CODE REVIEW

**Comment by emadurandal** [comment]
FYI,

My friend cx20 has updated the comparison page.
You can access WalkingLady example of each library from here.
https://github.com/cx20/gltf-test

**Comment by pjcozzi** [comment]
Thanks for the sample model!  It would be good for one more library (e.g., https://github.com/AnalyticalGraphicsInc/cesium/issues/4722) to confirm that this model is valid before we merge this.

You could also try the [glTF Validator](https://github.com/KhronosGroup/glTF-Validator) but that is for glTF 1.1 so it may report a few warnings/errors that do not apply to 1.0.

**Comment by emadurandal** [comment]
@pjcozzi Thank you!  I'll check the glTF Validator.

And breaking news. My friend @kyasbal-1994 (a talented university student)'s WebGL library Grimoire.js (https://grimoire.gl) has supported this animation model Just before.
https://i.gyazo.com/7b94744dc07f069f47d83cf9ca2da904.mp4
(I am surprised that he has overtaken the glTF support level I have built over half a year, in just one month from the start of work!)

After preparation, GrimoireJS's version of the example will be opened at @cx20's loader comparison page.

**Comment by kyasbal-1994** [comment]
@emadurandal Thanks for introducing my library.




I needs to note that I supported glTF feature as an extension and it is still beta.( there are performance problems and some of material bugs yet)
And I'm sorry but my library only have Japanese webpage yet.(Github page https://github.com/GrimoireGL/GrimoireJS is only the page written in English but a little bit old) I would prepare web pages written in English as soon as possible.

**Comment by pjcozzi** [comment]
@kyasbal-1994 could you please open a pull request in the glTF repo to add your engine to the [list of tools](https://github.com/KhronosGroup/glTF#loaders-and-viewers) supporting glTF?

**Comment by pjcozzi** [comment]
@kyasbal-1994 also your engine looks great!  We would welcome any other contributions you are able to make to the glTF community, for example, see https://github.com/KhronosGroup/glTF/issues/456

**Comment by emadurandal** [comment]
@kyasbal-1994 congrats!

BTW, It seems that three.js has supported this animation model.
https://github.com/mrdoob/three.js/pull/10319

I made this glTF data using Maya's OpenCollada Plugin & COLLADA2GLTF Converter.
So, to establish glTF workflow in Maya, being able to play this model may be one requirement for now.

**Comment by pjcozzi** [comment]
OK, sounds like it is not an issue with the model, thanks again for the contribution!

**Pull request merged**
