### PR TITLE
Adding SheenCloth asset

### PR DESCRIPTION
**Pull request by PatrickRyanMS**
Sample asset of a cloth simulated mesh with a custom texture including a sheen texture using KHR_materials_sheen extention in the file. The mesh is heavy due to the frequency and resolution of the folds in the cloth, but we make up some ground by using 256x256 tiling textures that are tiled 30 times in U and V to maximize resolution when close.

The sheen texture is pushing multiple colors into the material based on the textile design and we are passing a custom roughness in alpha as well to control the sheen levels in the material. 

The README contains some information about how the asset was made and screen captures of the asset running in the Babylon.js playground.

### CODE REVIEW

**Comment by emackey** [comment]
Thanks Patrick!  I'll mention this model at the PBR Next meeting on Monday.

**Comment by cx20** [comment]
I added this model to [gltf-test](https://cx20.github.io/gltf-test/)  as usual and tested it. The display results of some WebGL libraries are as follows.
Probably Babylon.js is the expected result, but at first glance it is difficult to determine which library uses the `KHR_materials_sheen` extension.

|Library|Result (small)|Result (large)|
|:---------------:|:---------------:|:---------------:|
|[three.js](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=SheenCloth&scale=50&type=glTF)|image|image|
|[Babylon.js](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=SheenCloth&scale=50&type=glTF)|image|image|
|[Filament](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=SheenCloth&scale=50&type=glTF)|image|image|
|[PlayCanvas](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=SheenCloth&scale=50&type=glTF)|image|image|

**Comment by bghgary** [comment]
This model has the KHR_materials_sheen extension marked as required. Looking at the results, I'm guessing only Babylon.js currently supports this extension? If so, then implementations are not respecting the extensions required property?

Looks like that's the case:
https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Positive/Compatibility (Model 05)

**Comment by donmccurdy** [comment]
three.js should be printing a warning about the unknown required extension, but isn't preventing the load. We don't implement `KHR_materials_sheen` yet.

**Review by donmccurdy — APPROVED** [review]

**Comment by donmccurdy** [comment]
Testing read/write in https://github.com/donmccurdy/glTF-Transform/pull/114, this looks good to me!

**Review by emackey — APPROVED** [review]
Manually validated with 2.0.0-dev.3.3 pre-release (which supports sheen).

**Pull request merged**
