### PR TITLE
Add Multiple UV Test model

### PR DESCRIPTION
**Pull request by 06wj**
screenshot
This model has two uv texture coordinates.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Looks good! This model works in BabylonJS but (as expected) appears wrong in three.js which does not yet support multiple UVs fully. I'm OK with merging it despite that, it is a good test case. :)

**Comment by 06wj** [comment]
@emackey Can this be merged to the ```master``` branch?

**Comment by emackey** [comment]
Thanks for your patience @06wj.  Can we show something better than a broken glTF logo when an engine doesn't support multi UVs?  Maybe an image of the message:

```
Multiple UVs
not supported
in this viewer
```

Or something along those lines?

**Comment by lexaknyazev** [comment]
We should also remove two empty nodes (with camera and lamp).

**Comment by 06wj** [comment]
@emackey  Update the model.
When engine doesn't support multi UVs, it will show the error message.

**Comment by lexaknyazev** [comment]
Not a strong opinion. why do we need an asset-provided camera for this sample? Is it aligned with other models in this repo?

**Comment by emackey** [comment]
> why do we need an asset-provided camera for this sample?

Not strictly needed but I don't think it hurts anything by its presence.  It doesn't appear to produce a validation message anymore.

**Comment by emackey** [comment]
No strong objections were reported here, so I'm merging this.  Let me know if anyone finds any issues.

**Pull request merged**
