### PR TITLE
 Norbert's glTF 2.0 sample models

### PR DESCRIPTION
**Pull request by McNopper**

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @McNopper.

@bghgary do you want to double check these before we merge?

**Comment by bghgary** [comment]
@pjcozzi I looked through the JSON files. The only thing that jumped out were the `TANGENT` and `BITANGENT` attributes on mesh. Do we want our sample models to include them?

**Comment by emackey** [comment]
Is this going to add conflicts with #28?

**Comment by McNopper** [comment]
Maybe I am not up to date anymore, but I thought either TANGENT4 or TANGENT/BITANGENT can be used:
https://github.com/KhronosGroup/glTF/issues/812

**Comment by bghgary** [comment]
The WG had some concerns with stored tangents and morph targets exceeding the mesh attribute limits of WebGL. The current plan is to not add stored tangents support to the core spec.

I'm currently trying to define what is the right math for calculating the tangent frame at runtime.

@McNopper Is it easy for you to remove the tangents/bitangents for now?

**Comment by McNopper** [comment]
My loader can currently do both - TANGENT4 and TANGENT/BITANGENT.
When exporting, I currently store TANGENT/BITANGENT but I can default to TANGENT4.
So, yes, these are just a few lines from my side.
Let me fix this and I will do another pull request.

**Comment by McNopper** [comment]
Okay, made another pull request:
https://github.com/KhronosGroup/glTF-Sample-Models/pull/42
Using TANGENT4 as default now.
Think I got the math right (using http://crytek.com/download/izfrey_siggraph2011.pdf).

**Pull request closed without merging**
