### PR TITLE
Removed technique states disable from brainstem binary

### PR DESCRIPTION
**Pull request by lasalvavida**
Fix for #2 and probably #15 as well

~~edit: I found some issues in this, please hold off for a little bit while I fix them~~

### CODE REVIEW

**Comment by lasalvavida** [comment]
Updated and squashed

**Comment by lasalvavida** [comment]
@pjcozzi

**Comment by pjcozzi** [comment]
@icechen1 this is the fix for https://github.com/KhronosGroup/glTF/pull/770 / #2.  Thanks again for catching this.

**Comment by pjcozzi** [comment]
@mre4ce @javagl this also fixes #15

**Pull request merged**
