### PR TITLE
New glTF models 

### PR DESCRIPTION
**Pull request by sbtron**
FYI working on adding new sample models.
Have FBX and Collada versions now but need to generate the glTF versions.
Starting with 3 models for now but many more in queue once we get the conversion process up and going.

Please don't merge yet.

### CODE REVIEW

**Comment by pjcozzi** [comment]
@sbtron for the COLLADA files perhaps try converting the big .tga files to .png or .jpg, then try the drag and drop converter here: http://cesiumjs.org/convertmodel.html

For general troubleshooting, check out this section from the Cesium tutorial: https://cesiumjs.org/tutorials/3D-Models-Tutorial/#converting-collada-to-gltf

**Comment by sbtron** [comment]
Some progress with models rendering in Cesium, Xeo and glBoost. but not in three.js/babylonJS using the gltf-test tools: 
sources: https://github.com/sbtron/gltf-test/tree/newsamplemodeltest
live: http://gltf-test.azurewebsites.net/

might be engine specific issues but still looking into it.

**Comment by pjcozzi** [comment]
Have you tested the glTF models with the validator (just a heads up it validates glTF 1.1, not 1.0): https://github.com/KhronosGroup/glTF-Validator

Also, I tried some examples like http://gltf-test.azurewebsites.net/examples/cesium/index.html?model=BarramundiFish&scale=0.05&type=glTF-Binary but the console reports:

> Failed to load resource: the server responded with a status of 404 (Not Found)
> http://gltf-test.azurewebsites.net/sampleModels/BarramundiFish/glTF-Binary/BarramundiFish.glb

**Comment by sbtron** [comment]
will try the validator. Are any of the tools generating 1.1 yet?

Haven't generated gltf binaries yet. The collada2gltf command line doesn't seem to have that option? The cesium website does seem to allow that are they different codebases? 

Incidentally I ended up using [assimp](https://github.com/assimp/assimp) to go from FBX to Collada and that seemed like a better conversion than the autodesk fbx to collada converter I was using earlier.

**Comment by javagl** [comment]
> Haven't generated gltf binaries yet. The collada2gltf command line doesn't seem to have that option? The cesium website does seem to allow that are they different codebases?

If I understood this correctly: The online converter uses COLLADA2GLTF to do the actual conversion drom DAE to glTF, but then uses https://github.com/AnalyticalGraphicsInc/gltf-pipeline as some sort of "post-processing" step to convert the resulting glTF into binary glTF.

**Comment by sbtron** [comment]
Was able to generate those glbs using the cesium website. Is there a pointer to how the common material models were created :)

**Comment by pjcozzi** [comment]
> Are any of the tools generating 1.1 yet?

Not that I am aware of, but gltf-pipeline will be able to convert 1.0 to 1.1 very soon: https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/191

There is also work towards upgrading COLLADA2GLTF to 1.1, but the pull request is not ready yet: https://github.com/KhronosGroup/COLLADA2GLTF/compare/master...lasalvavida:converter1.1

Both of these are by @lasalvavida.

> Is there a pointer to how the common material models were created :)

Which models in particular?

**Comment by sbtron** [comment]
Most models seem to have a Materials common version too which is why I was wondering if it was needed. e.g. https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/1.0/CesiumMilkTruck/glTF-MaterialsCommon https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/1.0/2CylinderEngine/glTF-MaterialsCommon

**Comment by pjcozzi** [comment]
@sbtron the milk truck model was converted with COLLADA2GLTF (using the -k option to generate materials common, see the bottom of [this page](https://github.com/KhronosGroup/COLLADA2GLTF)).

So you could go through COLLADA to generate this or we would be happy to still take the sample models without this variation.

**Comment by sbtron** [comment]
@pjcozzi lets get these three in while I work on fixing others

**Comment by cx20** [comment]
@sbtron I think that the gltf binary model, which was probably manually modified, is broken.

image

See:
https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_binary_glTF#binary-gltf-layout
Figure 1: Binary glTF layout.
image

**Comment by javagl** [comment]
Indeed, the length indicates 537164250 bytes... 

Since the `0x00` bytes have consistently been replaced by `0x20` (a `' '` space), I guess that the file was opened and saved with a *text* editor, and not with a *hex* editor. 

It seemed to work properly in https://github.com/sbtron/glTF-Sample-Models/blob/4f97c9b9484ca4b9f1f22707d3e7149cdfc9ff13/1.0/SmilingFace/glTF-Binary/SmilingFace.glb , by the way.

**Comment by sbtron** [comment]
Thanks I was manually tweaking those values to test things out. Updated now by regenerating the whole glb.

**Comment by cx20** [comment]
@sbtron I confirmed that Avocado.glb and BarramundiFish.glb have been modified.
However, SmilingFace.glb has not been repaired yet.

**Comment by cx20** [comment]
I tested the loading of 3 models with each latest WebGL library and confirmed that they are displayed correctly.
https://github.com/cx20/gltf-test
https://cx20.github.io/gltf-test/

**Comment by pjcozzi** [comment]
@sbtron could you open a separate pull request to add these models to the main [README.md](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/1.0/README.md)?

**Comment by javagl** [comment]
The .GLB versions of these models all seem to have an invalid field:

    .techniques.technique0.states.disable

Maybe these could be removed.

**Comment by pjcozzi** [comment]
Good eye, @javagl.  @sbtron could you fix these in a new PR?

**Pull request merged**
