### PR TITLE
morph target with sparse accessor that omitted bufferView sample

### PR DESCRIPTION
**Pull request by ousttrue**
```json
    {
// omit "bufferView" key
      "componentType": 5126,
      "count": 1968,

      "sparse": {
        "count": 208,
        "indices": {
          "bufferView": 4,
          "byteOffset": 0,
          "componentType": 5125
        },
        "values": {
          "bufferView": 5,
          "byteOffset": 0
        }
      },
      "type": "VEC3"
    },
```

This sample cause `BUFFER_VIEW_TARGET_OVERRIDE` to glTF validator.

> When it's omitted, the sparse accessor is initialized as an array of zeros of size (size of the accessor element) * (accessor.count) bytes

from https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#sparse-accessors

### CODE REVIEW

**Comment by cx20** [comment]
I think it's better to match the folder name with the file name.

|Folder Name     |File Name|
|:---------------|:--------|
|`Duck`/glTF       |`Duck`.gltf|
|`Duck`/glTF-Binary|`Duck`.glb |

Here are the proposed changes.

|before|after|
|:-----|:-----|
|`suzanne_sparse_morph`.glb |`SuzanneMorphSparse`.glb |

**Comment by cx20** [comment]
Currently, the validator produces the following errors Is there a problem with the schema?

```json
"messages": [
  {
    "code": "BUFFER_VIEW_TARGET_OVERRIDE",
    "message": "Override of previously set bufferView target or usage. Initial: 'VertexBuffer', new: 'Other'.",
    "severity": 0,
    "pointer": "/accessors/4/sparse/values/bufferView"
  },
  {
    "code": "BUFFER_VIEW_TARGET_OVERRIDE",
    "message": "Override of previously set bufferView target or usage. Initial: 'VertexBuffer', new: 'Other'.",
    "severity": 0,
    "pointer": "/accessors/5/sparse/values/bufferView"
  },
  {
    "code": "UNUSED_OBJECT",
    "message": "This object may be unused.",
    "severity": 2,
    "pointer": "/meshes/0/primitives/0/attributes/TEXCOORD_0"
  }
],
```

**Comment by ousttrue** [comment]
Thank you for your advice.
I corrected the filename.

I think `BUFFER_VIEW_TARGET_OVERRIDE` is because the value of bufferview is considered to be 0 if the accessor has sparse and bufferview is omitted.
bufferView0 is already used in vertexBuffer.

```json
// accessor.schema.json
     "bufferView": {
            "allOf": [ { "$ref": "glTFid.schema.json" } ],
            "description": "The index of the bufferView.",
            "gltf_detailedDescription": "The index of the bufferView. When not defined, accessor must be initialized with zeros; `sparse` property or extensions could override zeros with actual values."
        },

// glTFid.schema.json 
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "glTF Id",
    "type": "integer",
    "minimum": 0
}
```

I think the omitted bufferView should be interpreted as null.
If it is null, it seems better not to judge it as BUFFER_VIEW_TARGET_OVERRIDE.
Once this is merged, add a new issue to glTF-Validator.

**Comment by ousttrue** [comment]
I didn't really care about the `UNUSED_OBJECT` warning.

**Comment by lexaknyazev** [comment]
This asset is invalid. Buffer views 5 and 6 contain sparse values but have their `target`s set to `ARRAY_BUFFER`.

**Comment by ousttrue** [comment]
Thanks for the advice. 
The `BUFFER_VIEW_TARGET_OVERRIDE` has been resolved by removing the unnecessary ʻARRAY_BUFFER`.

**Comment by emackey** [comment]
Looks like the asset is valid now, thanks.

Would it be possible to add a glTF animation that exercises this morph target?  Many simple viewers don't have a control for a stand-alone morph target, and will only show movement if there's an animation attached.

Also, can you merge the upstream master branch into this branch?  Thanks!

**Comment by DrX3D** [comment]
@ousttrue : We are working on cleaning out the PR queue. Please address the issue above so this PR can be merged.

**Pull request merged**
